// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://prnzuoladzdixamlxmrv.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybnp1b2xhZHpkaXhhbWx4bXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDE2MzQsImV4cCI6MjA3MzI3NzYzNH0.67GZ9Ev4fIFD-V9rtMHHve6twvwG5jCjc0-F7_0StTM";
export const SUPABASE_FUNCTIONS_URL = "https://prnzuoladzdixamlxmrv.functions.supabase.co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});